---
openapi: 3.0.1
info:
  title: API V1
  version: v1
paths:
  "/doctors":
    get:
      summary: list doctors
      responses:
        '200':
          description: successful
    post:
      summary: create doctor
      responses:
        '200':
          description: successful
  "/doctors/{id}":
    parameters:
    - name: id
      in: path
      description: id
      required: true
      schema:
        type: string
    get:
      summary: show doctor
      responses:
        '200':
          description: successful
    patch:
      summary: update doctor
      responses:
        '200':
          description: successful
    put:
      summary: update doctor
      responses:
        '200':
          description: successful
    delete:
      summary: delete doctor
      responses:
        '200':
          description: successful
servers:
- url: https://{defaultHost}
  variables:
    defaultHost:
      default: www.example.com
